version: '2.15.1'

services:

##### Assessment Tools #####

  kali: 
    build: ./kali
    image: packethead/kali
    container_name: kali
    hostname: kali
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    tty: true
    networks:
      packethead:
        ipv4_address: 10.20.0.10
    volumes: 
      - /Users/em0ral/ContainerData/kali/:/root/kali 
      - ./kali/config/.tmux.conf:/root/.tmux.conf
    restart: unless-stopped

      #  modbus_server: 
      #    build: ./modbus
      #    image: packethead/modbus_server
      #    container_name: modbus_server
      #    hostname: modbus_server
      #    privileged: true
      #    sysctls:
      #      - net.ipv6.conf.all.disable_ipv6=0
      #    tty: true
      #    networks:
      #      packethead:
      #        ipv4_address: 10.20.0.100
      #    volumes: 
      #      - /Users/em0ral/Containers/modbus_server/:/modbus  
      #      - ./kali/config/.tmux.conf:/root/.tmux.conf
      #    restart: unless-stopped
 


  kali2:
    image: kasmweb/core-kali-rolling:1.13.0
    container_name: kali-gui
    hostname: kali-gui
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    user: 'root'
    tty: true
    shm_size: '512m'
    environment:
     VNC_PW: 'password'
    ports:
     - 6901:6901
    networks:
     packethead:
      ipv4_address: 10.20.0.250
    volumes: 
      - /Users/em0ral/ContainerData/kali-gui:/home/kasm-user/kali
      
##### Networks #####

networks:
 packethead:
  driver: bridge
  ipam:
    config:
      - subnet: 10.20.0.0/24
        gateway: 10.20.0.1
    

